// Generated by generate_cpu_tests.py. Do not edit.
#include "test_cpu.hpp"

#include <gtest/gtest.h>

TEST(GameboyCBOpcodeTest, test_00_json) {
    run_gameboy_cb_cpu_test_file("00.json");
}

TEST(GameboyCBOpcodeTest, test_01_json) {
    run_gameboy_cb_cpu_test_file("01.json");
}

TEST(GameboyCBOpcodeTest, test_02_json) {
    run_gameboy_cb_cpu_test_file("02.json");
}

TEST(GameboyCBOpcodeTest, test_03_json) {
    run_gameboy_cb_cpu_test_file("03.json");
}

TEST(GameboyCBOpcodeTest, test_04_json) {
    run_gameboy_cb_cpu_test_file("04.json");
}

TEST(GameboyCBOpcodeTest, test_05_json) {
    run_gameboy_cb_cpu_test_file("05.json");
}

TEST(GameboyCBOpcodeTest, test_06_json) {
    run_gameboy_cb_cpu_test_file("06.json");
}

TEST(GameboyCBOpcodeTest, test_07_json) {
    run_gameboy_cb_cpu_test_file("07.json");
}

TEST(GameboyCBOpcodeTest, test_08_json) {
    run_gameboy_cb_cpu_test_file("08.json");
}

TEST(GameboyCBOpcodeTest, test_09_json) {
    run_gameboy_cb_cpu_test_file("09.json");
}

TEST(GameboyCBOpcodeTest, test_0a_json) {
    run_gameboy_cb_cpu_test_file("0a.json");
}

TEST(GameboyCBOpcodeTest, test_0b_json) {
    run_gameboy_cb_cpu_test_file("0b.json");
}

TEST(GameboyCBOpcodeTest, test_0c_json) {
    run_gameboy_cb_cpu_test_file("0c.json");
}

TEST(GameboyCBOpcodeTest, test_0d_json) {
    run_gameboy_cb_cpu_test_file("0d.json");
}

TEST(GameboyCBOpcodeTest, test_0e_json) {
    run_gameboy_cb_cpu_test_file("0e.json");
}

TEST(GameboyCBOpcodeTest, test_0f_json) {
    run_gameboy_cb_cpu_test_file("0f.json");
}

TEST(GameboyCBOpcodeTest, test_10_json) {
    run_gameboy_cb_cpu_test_file("10.json");
}

TEST(GameboyCBOpcodeTest, test_11_json) {
    run_gameboy_cb_cpu_test_file("11.json");
}

TEST(GameboyCBOpcodeTest, test_12_json) {
    run_gameboy_cb_cpu_test_file("12.json");
}

TEST(GameboyCBOpcodeTest, test_13_json) {
    run_gameboy_cb_cpu_test_file("13.json");
}

TEST(GameboyCBOpcodeTest, test_14_json) {
    run_gameboy_cb_cpu_test_file("14.json");
}

TEST(GameboyCBOpcodeTest, test_15_json) {
    run_gameboy_cb_cpu_test_file("15.json");
}

TEST(GameboyCBOpcodeTest, test_16_json) {
    run_gameboy_cb_cpu_test_file("16.json");
}

TEST(GameboyCBOpcodeTest, test_17_json) {
    run_gameboy_cb_cpu_test_file("17.json");
}

TEST(GameboyCBOpcodeTest, test_18_json) {
    run_gameboy_cb_cpu_test_file("18.json");
}

TEST(GameboyCBOpcodeTest, test_19_json) {
    run_gameboy_cb_cpu_test_file("19.json");
}

TEST(GameboyCBOpcodeTest, test_1a_json) {
    run_gameboy_cb_cpu_test_file("1a.json");
}

TEST(GameboyCBOpcodeTest, test_1b_json) {
    run_gameboy_cb_cpu_test_file("1b.json");
}

TEST(GameboyCBOpcodeTest, test_1c_json) {
    run_gameboy_cb_cpu_test_file("1c.json");
}

TEST(GameboyCBOpcodeTest, test_1d_json) {
    run_gameboy_cb_cpu_test_file("1d.json");
}

TEST(GameboyCBOpcodeTest, test_1e_json) {
    run_gameboy_cb_cpu_test_file("1e.json");
}

TEST(GameboyCBOpcodeTest, test_1f_json) {
    run_gameboy_cb_cpu_test_file("1f.json");
}

TEST(GameboyCBOpcodeTest, test_20_json) {
    run_gameboy_cb_cpu_test_file("20.json");
}

TEST(GameboyCBOpcodeTest, test_21_json) {
    run_gameboy_cb_cpu_test_file("21.json");
}

TEST(GameboyCBOpcodeTest, test_22_json) {
    run_gameboy_cb_cpu_test_file("22.json");
}

TEST(GameboyCBOpcodeTest, test_23_json) {
    run_gameboy_cb_cpu_test_file("23.json");
}

TEST(GameboyCBOpcodeTest, test_24_json) {
    run_gameboy_cb_cpu_test_file("24.json");
}

TEST(GameboyCBOpcodeTest, test_25_json) {
    run_gameboy_cb_cpu_test_file("25.json");
}

TEST(GameboyCBOpcodeTest, test_26_json) {
    run_gameboy_cb_cpu_test_file("26.json");
}

TEST(GameboyCBOpcodeTest, test_27_json) {
    run_gameboy_cb_cpu_test_file("27.json");
}

TEST(GameboyCBOpcodeTest, test_28_json) {
    run_gameboy_cb_cpu_test_file("28.json");
}

TEST(GameboyCBOpcodeTest, test_29_json) {
    run_gameboy_cb_cpu_test_file("29.json");
}

TEST(GameboyCBOpcodeTest, test_2a_json) {
    run_gameboy_cb_cpu_test_file("2a.json");
}

TEST(GameboyCBOpcodeTest, test_2b_json) {
    run_gameboy_cb_cpu_test_file("2b.json");
}

TEST(GameboyCBOpcodeTest, test_2c_json) {
    run_gameboy_cb_cpu_test_file("2c.json");
}

TEST(GameboyCBOpcodeTest, test_2d_json) {
    run_gameboy_cb_cpu_test_file("2d.json");
}

TEST(GameboyCBOpcodeTest, test_2e_json) {
    run_gameboy_cb_cpu_test_file("2e.json");
}

TEST(GameboyCBOpcodeTest, test_2f_json) {
    run_gameboy_cb_cpu_test_file("2f.json");
}

TEST(GameboyCBOpcodeTest, test_30_json) {
    run_gameboy_cb_cpu_test_file("30.json");
}

TEST(GameboyCBOpcodeTest, test_31_json) {
    run_gameboy_cb_cpu_test_file("31.json");
}

TEST(GameboyCBOpcodeTest, test_32_json) {
    run_gameboy_cb_cpu_test_file("32.json");
}

TEST(GameboyCBOpcodeTest, test_33_json) {
    run_gameboy_cb_cpu_test_file("33.json");
}

TEST(GameboyCBOpcodeTest, test_34_json) {
    run_gameboy_cb_cpu_test_file("34.json");
}

TEST(GameboyCBOpcodeTest, test_35_json) {
    run_gameboy_cb_cpu_test_file("35.json");
}

TEST(GameboyCBOpcodeTest, test_36_json) {
    run_gameboy_cb_cpu_test_file("36.json");
}

TEST(GameboyCBOpcodeTest, test_37_json) {
    run_gameboy_cb_cpu_test_file("37.json");
}

TEST(GameboyCBOpcodeTest, test_38_json) {
    run_gameboy_cb_cpu_test_file("38.json");
}

TEST(GameboyCBOpcodeTest, test_39_json) {
    run_gameboy_cb_cpu_test_file("39.json");
}

TEST(GameboyCBOpcodeTest, test_3a_json) {
    run_gameboy_cb_cpu_test_file("3a.json");
}

TEST(GameboyCBOpcodeTest, test_3b_json) {
    run_gameboy_cb_cpu_test_file("3b.json");
}

TEST(GameboyCBOpcodeTest, test_3c_json) {
    run_gameboy_cb_cpu_test_file("3c.json");
}

TEST(GameboyCBOpcodeTest, test_3d_json) {
    run_gameboy_cb_cpu_test_file("3d.json");
}

TEST(GameboyCBOpcodeTest, test_3e_json) {
    run_gameboy_cb_cpu_test_file("3e.json");
}

TEST(GameboyCBOpcodeTest, test_3f_json) {
    run_gameboy_cb_cpu_test_file("3f.json");
}

TEST(GameboyCBOpcodeTest, test_40_json) {
    run_gameboy_cb_cpu_test_file("40.json");
}

TEST(GameboyCBOpcodeTest, test_41_json) {
    run_gameboy_cb_cpu_test_file("41.json");
}

TEST(GameboyCBOpcodeTest, test_42_json) {
    run_gameboy_cb_cpu_test_file("42.json");
}

TEST(GameboyCBOpcodeTest, test_43_json) {
    run_gameboy_cb_cpu_test_file("43.json");
}

TEST(GameboyCBOpcodeTest, test_44_json) {
    run_gameboy_cb_cpu_test_file("44.json");
}

TEST(GameboyCBOpcodeTest, test_45_json) {
    run_gameboy_cb_cpu_test_file("45.json");
}

TEST(GameboyCBOpcodeTest, test_46_json) {
    run_gameboy_cb_cpu_test_file("46.json");
}

TEST(GameboyCBOpcodeTest, test_47_json) {
    run_gameboy_cb_cpu_test_file("47.json");
}

TEST(GameboyCBOpcodeTest, test_48_json) {
    run_gameboy_cb_cpu_test_file("48.json");
}

TEST(GameboyCBOpcodeTest, test_49_json) {
    run_gameboy_cb_cpu_test_file("49.json");
}

TEST(GameboyCBOpcodeTest, test_4a_json) {
    run_gameboy_cb_cpu_test_file("4a.json");
}

TEST(GameboyCBOpcodeTest, test_4b_json) {
    run_gameboy_cb_cpu_test_file("4b.json");
}

TEST(GameboyCBOpcodeTest, test_4c_json) {
    run_gameboy_cb_cpu_test_file("4c.json");
}

TEST(GameboyCBOpcodeTest, test_4d_json) {
    run_gameboy_cb_cpu_test_file("4d.json");
}

TEST(GameboyCBOpcodeTest, test_4e_json) {
    run_gameboy_cb_cpu_test_file("4e.json");
}

TEST(GameboyCBOpcodeTest, test_4f_json) {
    run_gameboy_cb_cpu_test_file("4f.json");
}

TEST(GameboyCBOpcodeTest, test_50_json) {
    run_gameboy_cb_cpu_test_file("50.json");
}

TEST(GameboyCBOpcodeTest, test_51_json) {
    run_gameboy_cb_cpu_test_file("51.json");
}

TEST(GameboyCBOpcodeTest, test_52_json) {
    run_gameboy_cb_cpu_test_file("52.json");
}

TEST(GameboyCBOpcodeTest, test_53_json) {
    run_gameboy_cb_cpu_test_file("53.json");
}

TEST(GameboyCBOpcodeTest, test_54_json) {
    run_gameboy_cb_cpu_test_file("54.json");
}

TEST(GameboyCBOpcodeTest, test_55_json) {
    run_gameboy_cb_cpu_test_file("55.json");
}

TEST(GameboyCBOpcodeTest, test_56_json) {
    run_gameboy_cb_cpu_test_file("56.json");
}

TEST(GameboyCBOpcodeTest, test_57_json) {
    run_gameboy_cb_cpu_test_file("57.json");
}

TEST(GameboyCBOpcodeTest, test_58_json) {
    run_gameboy_cb_cpu_test_file("58.json");
}

TEST(GameboyCBOpcodeTest, test_59_json) {
    run_gameboy_cb_cpu_test_file("59.json");
}

TEST(GameboyCBOpcodeTest, test_5a_json) {
    run_gameboy_cb_cpu_test_file("5a.json");
}

TEST(GameboyCBOpcodeTest, test_5b_json) {
    run_gameboy_cb_cpu_test_file("5b.json");
}

TEST(GameboyCBOpcodeTest, test_5c_json) {
    run_gameboy_cb_cpu_test_file("5c.json");
}

TEST(GameboyCBOpcodeTest, test_5d_json) {
    run_gameboy_cb_cpu_test_file("5d.json");
}

TEST(GameboyCBOpcodeTest, test_5e_json) {
    run_gameboy_cb_cpu_test_file("5e.json");
}

TEST(GameboyCBOpcodeTest, test_5f_json) {
    run_gameboy_cb_cpu_test_file("5f.json");
}

TEST(GameboyCBOpcodeTest, test_60_json) {
    run_gameboy_cb_cpu_test_file("60.json");
}

TEST(GameboyCBOpcodeTest, test_61_json) {
    run_gameboy_cb_cpu_test_file("61.json");
}

TEST(GameboyCBOpcodeTest, test_62_json) {
    run_gameboy_cb_cpu_test_file("62.json");
}

TEST(GameboyCBOpcodeTest, test_63_json) {
    run_gameboy_cb_cpu_test_file("63.json");
}

TEST(GameboyCBOpcodeTest, test_64_json) {
    run_gameboy_cb_cpu_test_file("64.json");
}

TEST(GameboyCBOpcodeTest, test_65_json) {
    run_gameboy_cb_cpu_test_file("65.json");
}

TEST(GameboyCBOpcodeTest, test_66_json) {
    run_gameboy_cb_cpu_test_file("66.json");
}

TEST(GameboyCBOpcodeTest, test_67_json) {
    run_gameboy_cb_cpu_test_file("67.json");
}

TEST(GameboyCBOpcodeTest, test_68_json) {
    run_gameboy_cb_cpu_test_file("68.json");
}

TEST(GameboyCBOpcodeTest, test_69_json) {
    run_gameboy_cb_cpu_test_file("69.json");
}

TEST(GameboyCBOpcodeTest, test_6a_json) {
    run_gameboy_cb_cpu_test_file("6a.json");
}

TEST(GameboyCBOpcodeTest, test_6b_json) {
    run_gameboy_cb_cpu_test_file("6b.json");
}

TEST(GameboyCBOpcodeTest, test_6c_json) {
    run_gameboy_cb_cpu_test_file("6c.json");
}

TEST(GameboyCBOpcodeTest, test_6d_json) {
    run_gameboy_cb_cpu_test_file("6d.json");
}

TEST(GameboyCBOpcodeTest, test_6e_json) {
    run_gameboy_cb_cpu_test_file("6e.json");
}

TEST(GameboyCBOpcodeTest, test_6f_json) {
    run_gameboy_cb_cpu_test_file("6f.json");
}

TEST(GameboyCBOpcodeTest, test_70_json) {
    run_gameboy_cb_cpu_test_file("70.json");
}

TEST(GameboyCBOpcodeTest, test_71_json) {
    run_gameboy_cb_cpu_test_file("71.json");
}

TEST(GameboyCBOpcodeTest, test_72_json) {
    run_gameboy_cb_cpu_test_file("72.json");
}

TEST(GameboyCBOpcodeTest, test_73_json) {
    run_gameboy_cb_cpu_test_file("73.json");
}

TEST(GameboyCBOpcodeTest, test_74_json) {
    run_gameboy_cb_cpu_test_file("74.json");
}

TEST(GameboyCBOpcodeTest, test_75_json) {
    run_gameboy_cb_cpu_test_file("75.json");
}

TEST(GameboyCBOpcodeTest, test_76_json) {
    run_gameboy_cb_cpu_test_file("76.json");
}

TEST(GameboyCBOpcodeTest, test_77_json) {
    run_gameboy_cb_cpu_test_file("77.json");
}

TEST(GameboyCBOpcodeTest, test_78_json) {
    run_gameboy_cb_cpu_test_file("78.json");
}

TEST(GameboyCBOpcodeTest, test_79_json) {
    run_gameboy_cb_cpu_test_file("79.json");
}

TEST(GameboyCBOpcodeTest, test_7a_json) {
    run_gameboy_cb_cpu_test_file("7a.json");
}

TEST(GameboyCBOpcodeTest, test_7b_json) {
    run_gameboy_cb_cpu_test_file("7b.json");
}

TEST(GameboyCBOpcodeTest, test_7c_json) {
    run_gameboy_cb_cpu_test_file("7c.json");
}

TEST(GameboyCBOpcodeTest, test_7d_json) {
    run_gameboy_cb_cpu_test_file("7d.json");
}

TEST(GameboyCBOpcodeTest, test_7e_json) {
    run_gameboy_cb_cpu_test_file("7e.json");
}

TEST(GameboyCBOpcodeTest, test_7f_json) {
    run_gameboy_cb_cpu_test_file("7f.json");
}

TEST(GameboyCBOpcodeTest, test_80_json) {
    run_gameboy_cb_cpu_test_file("80.json");
}

TEST(GameboyCBOpcodeTest, test_81_json) {
    run_gameboy_cb_cpu_test_file("81.json");
}

TEST(GameboyCBOpcodeTest, test_82_json) {
    run_gameboy_cb_cpu_test_file("82.json");
}

TEST(GameboyCBOpcodeTest, test_83_json) {
    run_gameboy_cb_cpu_test_file("83.json");
}

TEST(GameboyCBOpcodeTest, test_84_json) {
    run_gameboy_cb_cpu_test_file("84.json");
}

TEST(GameboyCBOpcodeTest, test_85_json) {
    run_gameboy_cb_cpu_test_file("85.json");
}

TEST(GameboyCBOpcodeTest, test_86_json) {
    run_gameboy_cb_cpu_test_file("86.json");
}

TEST(GameboyCBOpcodeTest, test_87_json) {
    run_gameboy_cb_cpu_test_file("87.json");
}

TEST(GameboyCBOpcodeTest, test_88_json) {
    run_gameboy_cb_cpu_test_file("88.json");
}

TEST(GameboyCBOpcodeTest, test_89_json) {
    run_gameboy_cb_cpu_test_file("89.json");
}

TEST(GameboyCBOpcodeTest, test_8a_json) {
    run_gameboy_cb_cpu_test_file("8a.json");
}

TEST(GameboyCBOpcodeTest, test_8b_json) {
    run_gameboy_cb_cpu_test_file("8b.json");
}

TEST(GameboyCBOpcodeTest, test_8c_json) {
    run_gameboy_cb_cpu_test_file("8c.json");
}

TEST(GameboyCBOpcodeTest, test_8d_json) {
    run_gameboy_cb_cpu_test_file("8d.json");
}

TEST(GameboyCBOpcodeTest, test_8e_json) {
    run_gameboy_cb_cpu_test_file("8e.json");
}

TEST(GameboyCBOpcodeTest, test_8f_json) {
    run_gameboy_cb_cpu_test_file("8f.json");
}

TEST(GameboyCBOpcodeTest, test_90_json) {
    run_gameboy_cb_cpu_test_file("90.json");
}

TEST(GameboyCBOpcodeTest, test_91_json) {
    run_gameboy_cb_cpu_test_file("91.json");
}

TEST(GameboyCBOpcodeTest, test_92_json) {
    run_gameboy_cb_cpu_test_file("92.json");
}

TEST(GameboyCBOpcodeTest, test_93_json) {
    run_gameboy_cb_cpu_test_file("93.json");
}

TEST(GameboyCBOpcodeTest, test_94_json) {
    run_gameboy_cb_cpu_test_file("94.json");
}

TEST(GameboyCBOpcodeTest, test_95_json) {
    run_gameboy_cb_cpu_test_file("95.json");
}

TEST(GameboyCBOpcodeTest, test_96_json) {
    run_gameboy_cb_cpu_test_file("96.json");
}

TEST(GameboyCBOpcodeTest, test_97_json) {
    run_gameboy_cb_cpu_test_file("97.json");
}

TEST(GameboyCBOpcodeTest, test_98_json) {
    run_gameboy_cb_cpu_test_file("98.json");
}

TEST(GameboyCBOpcodeTest, test_99_json) {
    run_gameboy_cb_cpu_test_file("99.json");
}

TEST(GameboyCBOpcodeTest, test_9a_json) {
    run_gameboy_cb_cpu_test_file("9a.json");
}

TEST(GameboyCBOpcodeTest, test_9b_json) {
    run_gameboy_cb_cpu_test_file("9b.json");
}

TEST(GameboyCBOpcodeTest, test_9c_json) {
    run_gameboy_cb_cpu_test_file("9c.json");
}

TEST(GameboyCBOpcodeTest, test_9d_json) {
    run_gameboy_cb_cpu_test_file("9d.json");
}

TEST(GameboyCBOpcodeTest, test_9e_json) {
    run_gameboy_cb_cpu_test_file("9e.json");
}

TEST(GameboyCBOpcodeTest, test_9f_json) {
    run_gameboy_cb_cpu_test_file("9f.json");
}

TEST(GameboyCBOpcodeTest, a0_json) {
    run_gameboy_cb_cpu_test_file("a0.json");
}

TEST(GameboyCBOpcodeTest, a1_json) {
    run_gameboy_cb_cpu_test_file("a1.json");
}

TEST(GameboyCBOpcodeTest, a2_json) {
    run_gameboy_cb_cpu_test_file("a2.json");
}

TEST(GameboyCBOpcodeTest, a3_json) {
    run_gameboy_cb_cpu_test_file("a3.json");
}

TEST(GameboyCBOpcodeTest, a4_json) {
    run_gameboy_cb_cpu_test_file("a4.json");
}

TEST(GameboyCBOpcodeTest, a5_json) {
    run_gameboy_cb_cpu_test_file("a5.json");
}

TEST(GameboyCBOpcodeTest, a6_json) {
    run_gameboy_cb_cpu_test_file("a6.json");
}

TEST(GameboyCBOpcodeTest, a7_json) {
    run_gameboy_cb_cpu_test_file("a7.json");
}

TEST(GameboyCBOpcodeTest, a8_json) {
    run_gameboy_cb_cpu_test_file("a8.json");
}

TEST(GameboyCBOpcodeTest, a9_json) {
    run_gameboy_cb_cpu_test_file("a9.json");
}

TEST(GameboyCBOpcodeTest, aa_json) {
    run_gameboy_cb_cpu_test_file("aa.json");
}

TEST(GameboyCBOpcodeTest, ab_json) {
    run_gameboy_cb_cpu_test_file("ab.json");
}

TEST(GameboyCBOpcodeTest, ac_json) {
    run_gameboy_cb_cpu_test_file("ac.json");
}

TEST(GameboyCBOpcodeTest, ad_json) {
    run_gameboy_cb_cpu_test_file("ad.json");
}

TEST(GameboyCBOpcodeTest, ae_json) {
    run_gameboy_cb_cpu_test_file("ae.json");
}

TEST(GameboyCBOpcodeTest, af_json) {
    run_gameboy_cb_cpu_test_file("af.json");
}

TEST(GameboyCBOpcodeTest, b0_json) {
    run_gameboy_cb_cpu_test_file("b0.json");
}

TEST(GameboyCBOpcodeTest, b1_json) {
    run_gameboy_cb_cpu_test_file("b1.json");
}

TEST(GameboyCBOpcodeTest, b2_json) {
    run_gameboy_cb_cpu_test_file("b2.json");
}

TEST(GameboyCBOpcodeTest, b3_json) {
    run_gameboy_cb_cpu_test_file("b3.json");
}

TEST(GameboyCBOpcodeTest, b4_json) {
    run_gameboy_cb_cpu_test_file("b4.json");
}

TEST(GameboyCBOpcodeTest, b5_json) {
    run_gameboy_cb_cpu_test_file("b5.json");
}

TEST(GameboyCBOpcodeTest, b6_json) {
    run_gameboy_cb_cpu_test_file("b6.json");
}

TEST(GameboyCBOpcodeTest, b7_json) {
    run_gameboy_cb_cpu_test_file("b7.json");
}

TEST(GameboyCBOpcodeTest, b8_json) {
    run_gameboy_cb_cpu_test_file("b8.json");
}

TEST(GameboyCBOpcodeTest, b9_json) {
    run_gameboy_cb_cpu_test_file("b9.json");
}

TEST(GameboyCBOpcodeTest, ba_json) {
    run_gameboy_cb_cpu_test_file("ba.json");
}

TEST(GameboyCBOpcodeTest, bb_json) {
    run_gameboy_cb_cpu_test_file("bb.json");
}

TEST(GameboyCBOpcodeTest, bc_json) {
    run_gameboy_cb_cpu_test_file("bc.json");
}

TEST(GameboyCBOpcodeTest, bd_json) {
    run_gameboy_cb_cpu_test_file("bd.json");
}

TEST(GameboyCBOpcodeTest, be_json) {
    run_gameboy_cb_cpu_test_file("be.json");
}

TEST(GameboyCBOpcodeTest, bf_json) {
    run_gameboy_cb_cpu_test_file("bf.json");
}

TEST(GameboyCBOpcodeTest, c0_json) {
    run_gameboy_cb_cpu_test_file("c0.json");
}

TEST(GameboyCBOpcodeTest, c1_json) {
    run_gameboy_cb_cpu_test_file("c1.json");
}

TEST(GameboyCBOpcodeTest, c2_json) {
    run_gameboy_cb_cpu_test_file("c2.json");
}

TEST(GameboyCBOpcodeTest, c3_json) {
    run_gameboy_cb_cpu_test_file("c3.json");
}

TEST(GameboyCBOpcodeTest, c4_json) {
    run_gameboy_cb_cpu_test_file("c4.json");
}

TEST(GameboyCBOpcodeTest, c5_json) {
    run_gameboy_cb_cpu_test_file("c5.json");
}

TEST(GameboyCBOpcodeTest, c6_json) {
    run_gameboy_cb_cpu_test_file("c6.json");
}

TEST(GameboyCBOpcodeTest, c7_json) {
    run_gameboy_cb_cpu_test_file("c7.json");
}

TEST(GameboyCBOpcodeTest, c8_json) {
    run_gameboy_cb_cpu_test_file("c8.json");
}

TEST(GameboyCBOpcodeTest, c9_json) {
    run_gameboy_cb_cpu_test_file("c9.json");
}

TEST(GameboyCBOpcodeTest, ca_json) {
    run_gameboy_cb_cpu_test_file("ca.json");
}

TEST(GameboyCBOpcodeTest, cb_json) {
    run_gameboy_cb_cpu_test_file("cb.json");
}

TEST(GameboyCBOpcodeTest, cc_json) {
    run_gameboy_cb_cpu_test_file("cc.json");
}

TEST(GameboyCBOpcodeTest, cd_json) {
    run_gameboy_cb_cpu_test_file("cd.json");
}

TEST(GameboyCBOpcodeTest, ce_json) {
    run_gameboy_cb_cpu_test_file("ce.json");
}

TEST(GameboyCBOpcodeTest, cf_json) {
    run_gameboy_cb_cpu_test_file("cf.json");
}

TEST(GameboyCBOpcodeTest, d0_json) {
    run_gameboy_cb_cpu_test_file("d0.json");
}

TEST(GameboyCBOpcodeTest, d1_json) {
    run_gameboy_cb_cpu_test_file("d1.json");
}

TEST(GameboyCBOpcodeTest, d2_json) {
    run_gameboy_cb_cpu_test_file("d2.json");
}

TEST(GameboyCBOpcodeTest, d3_json) {
    run_gameboy_cb_cpu_test_file("d3.json");
}

TEST(GameboyCBOpcodeTest, d4_json) {
    run_gameboy_cb_cpu_test_file("d4.json");
}

TEST(GameboyCBOpcodeTest, d5_json) {
    run_gameboy_cb_cpu_test_file("d5.json");
}

TEST(GameboyCBOpcodeTest, d6_json) {
    run_gameboy_cb_cpu_test_file("d6.json");
}

TEST(GameboyCBOpcodeTest, d7_json) {
    run_gameboy_cb_cpu_test_file("d7.json");
}

TEST(GameboyCBOpcodeTest, d8_json) {
    run_gameboy_cb_cpu_test_file("d8.json");
}

TEST(GameboyCBOpcodeTest, d9_json) {
    run_gameboy_cb_cpu_test_file("d9.json");
}

TEST(GameboyCBOpcodeTest, da_json) {
    run_gameboy_cb_cpu_test_file("da.json");
}

TEST(GameboyCBOpcodeTest, db_json) {
    run_gameboy_cb_cpu_test_file("db.json");
}

TEST(GameboyCBOpcodeTest, dc_json) {
    run_gameboy_cb_cpu_test_file("dc.json");
}

TEST(GameboyCBOpcodeTest, dd_json) {
    run_gameboy_cb_cpu_test_file("dd.json");
}

TEST(GameboyCBOpcodeTest, de_json) {
    run_gameboy_cb_cpu_test_file("de.json");
}

TEST(GameboyCBOpcodeTest, df_json) {
    run_gameboy_cb_cpu_test_file("df.json");
}

TEST(GameboyCBOpcodeTest, e0_json) {
    run_gameboy_cb_cpu_test_file("e0.json");
}

TEST(GameboyCBOpcodeTest, e1_json) {
    run_gameboy_cb_cpu_test_file("e1.json");
}

TEST(GameboyCBOpcodeTest, e2_json) {
    run_gameboy_cb_cpu_test_file("e2.json");
}

TEST(GameboyCBOpcodeTest, e3_json) {
    run_gameboy_cb_cpu_test_file("e3.json");
}

TEST(GameboyCBOpcodeTest, e4_json) {
    run_gameboy_cb_cpu_test_file("e4.json");
}

TEST(GameboyCBOpcodeTest, e5_json) {
    run_gameboy_cb_cpu_test_file("e5.json");
}

TEST(GameboyCBOpcodeTest, e6_json) {
    run_gameboy_cb_cpu_test_file("e6.json");
}

TEST(GameboyCBOpcodeTest, e7_json) {
    run_gameboy_cb_cpu_test_file("e7.json");
}

TEST(GameboyCBOpcodeTest, e8_json) {
    run_gameboy_cb_cpu_test_file("e8.json");
}

TEST(GameboyCBOpcodeTest, e9_json) {
    run_gameboy_cb_cpu_test_file("e9.json");
}

TEST(GameboyCBOpcodeTest, ea_json) {
    run_gameboy_cb_cpu_test_file("ea.json");
}

TEST(GameboyCBOpcodeTest, eb_json) {
    run_gameboy_cb_cpu_test_file("eb.json");
}

TEST(GameboyCBOpcodeTest, ec_json) {
    run_gameboy_cb_cpu_test_file("ec.json");
}

TEST(GameboyCBOpcodeTest, ed_json) {
    run_gameboy_cb_cpu_test_file("ed.json");
}

TEST(GameboyCBOpcodeTest, ee_json) {
    run_gameboy_cb_cpu_test_file("ee.json");
}

TEST(GameboyCBOpcodeTest, ef_json) {
    run_gameboy_cb_cpu_test_file("ef.json");
}

TEST(GameboyCBOpcodeTest, f0_json) {
    run_gameboy_cb_cpu_test_file("f0.json");
}

TEST(GameboyCBOpcodeTest, f1_json) {
    run_gameboy_cb_cpu_test_file("f1.json");
}

TEST(GameboyCBOpcodeTest, f2_json) {
    run_gameboy_cb_cpu_test_file("f2.json");
}

TEST(GameboyCBOpcodeTest, f3_json) {
    run_gameboy_cb_cpu_test_file("f3.json");
}

TEST(GameboyCBOpcodeTest, f4_json) {
    run_gameboy_cb_cpu_test_file("f4.json");
}

TEST(GameboyCBOpcodeTest, f5_json) {
    run_gameboy_cb_cpu_test_file("f5.json");
}

TEST(GameboyCBOpcodeTest, f6_json) {
    run_gameboy_cb_cpu_test_file("f6.json");
}

TEST(GameboyCBOpcodeTest, f7_json) {
    run_gameboy_cb_cpu_test_file("f7.json");
}

TEST(GameboyCBOpcodeTest, f8_json) {
    run_gameboy_cb_cpu_test_file("f8.json");
}

TEST(GameboyCBOpcodeTest, f9_json) {
    run_gameboy_cb_cpu_test_file("f9.json");
}

TEST(GameboyCBOpcodeTest, fa_json) {
    run_gameboy_cb_cpu_test_file("fa.json");
}

TEST(GameboyCBOpcodeTest, fb_json) {
    run_gameboy_cb_cpu_test_file("fb.json");
}

TEST(GameboyCBOpcodeTest, fc_json) {
    run_gameboy_cb_cpu_test_file("fc.json");
}

TEST(GameboyCBOpcodeTest, fd_json) {
    run_gameboy_cb_cpu_test_file("fd.json");
}

TEST(GameboyCBOpcodeTest, fe_json) {
    run_gameboy_cb_cpu_test_file("fe.json");
}

TEST(GameboyCBOpcodeTest, ff_json) {
    run_gameboy_cb_cpu_test_file("ff.json");
}
