#!/usr/bin/env python3

import argparse
import fnmatch
import re
import subprocess
from pathlib import Path


def test_name(path: Path) -> str:
    name = re.sub(r"[^A-Za-z0-9_]", "_", path.name.removesuffix(".bin"))
    if not name or name[0].isdigit():
        name = f"test_{name}"
    return name


def find_files(input_dir: Path, pattern: str) -> list[Path]:
    files = sorted(input_dir.glob(pattern))
    if files:
        return files

    existing_parent = input_dir
    while not existing_parent.exists() and existing_parent != existing_parent.parent:
        existing_parent = existing_parent.parent
    result = subprocess.run(
        ["git", "-C", str(existing_parent), "ls-tree", "-r", "--name-only", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    git_root = Path(
        subprocess.run(
            ["git", "-C", str(existing_parent), "rev-parse", "--show-toplevel"],
            check=True,
            capture_output=True,
            text=True,
        ).stdout.strip()
    )
    relative_dir = input_dir.relative_to(git_root)
    return sorted(
        git_root / name
        for name in result.stdout.splitlines()
        if Path(name).parent == relative_dir and fnmatch.fnmatch(Path(name).name, pattern)
    )


def generate(input_dir: Path, pattern: str, suite: str, runner: str) -> str:
    files = find_files(input_dir, pattern)
    if not files:
        raise ValueError(f"no {pattern} test files found in {input_dir}")

    lines = [
        "// Generated by generate_cpu_tests.py. Do not edit.",
        '#include "test_cpu.hpp"',
        "",
        "#include <gtest/gtest.h>",
        "",
    ]
    names: set[str] = set()
    for path in files:
        name = test_name(path)
        if name in names:
            raise ValueError(f"duplicate generated test name: {name}")
        names.add(name)
        lines.extend(
            [
                f"TEST({suite}, {name}) {{",
                f'    {runner}("{path.name}");',
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate one GoogleTest per CPU test data file")
    parser.add_argument("--input-dir", required=True, type=Path)
    parser.add_argument("--pattern", required=True)
    parser.add_argument("--suite", required=True)
    parser.add_argument("--runner", required=True)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    content = generate(args.input_dir, args.pattern, args.suite, args.runner)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text() != content:
        args.output.write_text(content)


if __name__ == "__main__":
    main()
