// Generated by generate_cpu_tests.py. Do not edit.
#include "test_cpu.hpp"

#include <gtest/gtest.h>

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_add_cmp_mov_hi_json) {
    run_cpu_test_file("thumb_add_cmp_mov_hi.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_add_sp_or_pc_json) {
    run_cpu_test_file("thumb_add_sp_or_pc.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_add_sub_json) {
    run_cpu_test_file("thumb_add_sub.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_add_sub_sp_json) {
    run_cpu_test_file("thumb_add_sub_sp.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_b_json) {
    run_cpu_test_file("thumb_b.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_bcc_json) {
    run_cpu_test_file("thumb_bcc.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_bl_blx_prefix_json) {
    run_cpu_test_file("thumb_bl_blx_prefix.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_bl_suffix_json) {
    run_cpu_test_file("thumb_bl_suffix.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_bx_json) {
    run_cpu_test_file("thumb_bx.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_data_proc_json) {
    run_cpu_test_file("thumb_data_proc.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldm_stm_json) {
    run_cpu_test_file("thumb_ldm_stm.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldr_pc_rel_json) {
    run_cpu_test_file("thumb_ldr_pc_rel.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldr_str_imm_offset_json) {
    run_cpu_test_file("thumb_ldr_str_imm_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldr_str_reg_offset_json) {
    run_cpu_test_file("thumb_ldr_str_reg_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldr_str_sp_rel_json) {
    run_cpu_test_file("thumb_ldr_str_sp_rel.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldrb_strb_imm_offset_json) {
    run_cpu_test_file("thumb_ldrb_strb_imm_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldrh_strh_imm_offset_json) {
    run_cpu_test_file("thumb_ldrh_strh_imm_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldrh_strh_reg_offset_json) {
    run_cpu_test_file("thumb_ldrh_strh_reg_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldrsb_strb_reg_offset_json) {
    run_cpu_test_file("thumb_ldrsb_strb_reg_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_ldrsh_ldrsb_reg_offset_json) {
    run_cpu_test_file("thumb_ldrsh_ldrsb_reg_offset.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_lsl_lsr_asr_json) {
    run_cpu_test_file("thumb_lsl_lsr_asr.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_mov_cmp_add_sub_json) {
    run_cpu_test_file("thumb_mov_cmp_add_sub.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_push_pop_json) {
    run_cpu_test_file("thumb_push_pop.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_swi_json) {
    run_cpu_test_file("thumb_swi.json.bin");
}

TEST(GameboyAdvanceTHUMBOpcodeTest, thumb_undefined_bcc_json) {
    run_cpu_test_file("thumb_undefined_bcc.json.bin");
}
