// Generated by generate_cpu_tests.py. Do not edit.
#include "test_cpu.hpp"

#include <gtest/gtest.h>

TEST(GameboyAdvanceARMOpcodeTest, arm_b_bl_json) {
    run_cpu_test_file("arm_b_bl.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_bx_json) {
    run_cpu_test_file("arm_bx.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_cdp_json) {
    run_cpu_test_file("arm_cdp.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_data_proc_immediate_json) {
    run_cpu_test_file("arm_data_proc_immediate.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_data_proc_immediate_shift_json) {
    run_cpu_test_file("arm_data_proc_immediate_shift.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_data_proc_register_shift_json) {
    run_cpu_test_file("arm_data_proc_register_shift.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_ldm_stm_json) {
    run_cpu_test_file("arm_ldm_stm.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_ldr_str_immediate_offset_json) {
    run_cpu_test_file("arm_ldr_str_immediate_offset.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_ldr_str_register_offset_json) {
    run_cpu_test_file("arm_ldr_str_register_offset.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_ldrh_strh_json) {
    run_cpu_test_file("arm_ldrh_strh.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_ldrsb_ldrsh_json) {
    run_cpu_test_file("arm_ldrsb_ldrsh.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_mcr_mrc_json) {
    run_cpu_test_file("arm_mcr_mrc.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_mrs_json) {
    run_cpu_test_file("arm_mrs.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_msr_imm_json) {
    run_cpu_test_file("arm_msr_imm.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_msr_reg_json) {
    run_cpu_test_file("arm_msr_reg.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_mul_mla_json) {
    run_cpu_test_file("arm_mul_mla.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_mull_mlal_json) {
    run_cpu_test_file("arm_mull_mlal.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_stc_ldc_json) {
    run_cpu_test_file("arm_stc_ldc.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_swi_json) {
    run_cpu_test_file("arm_swi.json.bin");
}

TEST(GameboyAdvanceARMOpcodeTest, arm_swp_json) {
    run_cpu_test_file("arm_swp.json.bin");
}
